apiVersion: v1
kind: Service
metadata:
  name: $NODE_APP_NAME-loadbalancer
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: $NODE_APP_NAME-service
spec:
  type: LoadBalancer
  selector:
    app: $NODE_APP_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000